--- # AWS EC2 Instance Communication Shell Command
- hosts: aws
  remote_user: ec2-user
  become: sudo 
  gather_facts: yes
  connection: ssh
  tasks:
  - name: Execute a shell Command for Listing the Directory
    shell: ls -al ~ 
    register: site_result
  - name: Display the result in JSON format
    debug: var=site-result
