--- # Gather EC2 facts from remote instance
- hosts: aws
  remote_user: ec2-user
  become: yes
  connection: ssh
  gather_facts: yes
  tasks:
  - name: Gather the EC2 Facts about running EC2 
    action: ec2_facts
  - name: Display instance type
    debug: msg='{{ ansible_ec2_instance_type }}'
